name: Recs Template SDK
on:
  pull_request:
  push:
    branches:
      - master
defaults:
  run:
    shell: bash
jobs:
  test:
    name: Build Test 🧪
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        id: checkout-branch-from-master
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 10.15.1

      - name: Check Cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Deploy staging
        run: yarn deploy_staging
